language: python
python:
  - "2.7"
addons:
  apt:
    sources:
    packages:
      - blender
before_script:
  - blender -v
install:
  - echo $TRAVIS_BUILD_DIR
  - tests/scripts/install_blender.sh $TRAVIS_BUILD_DIR
  - sudo ln -s $TRAVIS_BUILD_DIR/BlenderSync $BLENDER_FOLDER/2.79/scripts/addons/BlenderSync
script:
  - python tests.py $BLENDER_EXEC $TRAVIS_BUILD_DIR
after_failure:
  - echo $BLENDER_FOLDER
  - echo $BLENDER_EXEC
